site:
  title: Drum Pattern Library
  start_page: drum-patterns::index.adoc

content:
  sources:
    - url: .
      branches: HEAD

asciidoc:
  extensions:
    - ./lib/drum-pattern-block.js

ui:
  bundle:
    url: ./ui-bundle
  supplemental_files: ./supplemental-ui

output:
  dir: ./build/site
